version: '3.8'

services:
  # PostgreSQL Database - DEBE INICIAR PRIMERO
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=misviaticos_control
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - misviaticos-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # MisViaticos API - EJECUTA DESPUÉS DE POSTGRES
  misviaticos-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - POSTGRESQL_CONTROL_HOST=postgres
      - POSTGRESQL_NODE1_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./email_templates:/app/email_templates:ro
    networks:
      - misviaticos-network

  # Redis for caching and rate limiting
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - misviaticos-network

  # MinIO (S3 compatible) for local development
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - misviaticos-network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  misviaticos-network:
    driver: bridge