/* ===========
   3.  COMUNAS
   =========== */

INSERT INTO commune (id, region_id, name) VALUES
-- Arica y Parinacota (AP)
('arica'         ,'AP','Arica'),
('camarones'     ,'AP','Camarones'),
('general-lagos' ,'AP','General Lagos'),
('putre'         ,'AP','Putre'),

-- Tarapacá (TA)
('alto-hospicio' ,'TA','Alto Hospicio'),
('camina'        ,'TA','Camiña'),
('colchane'      ,'TA','Colchane'),
('huara'         ,'TA','Huara'),
('iquique'       ,'TA','Iquique'),
('pica'          ,'TA','Pica'),
('pozo-almonte'  ,'TA','Pozo Almonte'),

-- Antofagasta (AN)
('antofagasta'          ,'AN','Antofagasta'),
('calama'               ,'AN','Calama'),
('maria-elena'          ,'AN','María Elena'),
('mejillones'           ,'AN','Mejillones'),
('ollague'              ,'AN','Ollagüe'),
('san-pedro-de-atacama' ,'AN','San Pedro de Atacama'),
('sierra-gorda'         ,'AN','Sierra Gorda'),
('taltal'               ,'AN','Taltal'),
('tocopilla'            ,'AN','Tocopilla'),

-- Atacama (AT)
('alto-del-carmen' ,'AT','Alto del Carmen'),
('caldera'         ,'AT','Caldera'),
('chanaral'        ,'AT','Chañaral'),
('copiapo'         ,'AT','Copiapó'),
('diego-de-almagro','AT','Diego de Almagro'),
('freirina'        ,'AT','Freirina'),
('huasco'          ,'AT','Huasco'),
('tierra-amarilla' ,'AT','Tierra Amarilla'),
('vallenar'        ,'AT','Vallenar'),

-- Coquimbo (CO)
('andacollo'    ,'CO','Andacollo'),
('canela'       ,'CO','Canela'),
('combarbala'   ,'CO','Combarbalá'),
('coquimbo'     ,'CO','Coquimbo'),
('illapel'      ,'CO','Illapel'),
('la-higuera'   ,'CO','La Higuera'),
('la-serena'    ,'CO','La Serena'),
('los-vilos'    ,'CO','Los Vilos'),
('monte-patria' ,'CO','Monte Patria'),
('ovalle'       ,'CO','Ovalle'),
('paiguano'     ,'CO','Paiguano'),
('punitaqui'    ,'CO','Punitaqui'),
('rio-hurtado'  ,'CO','Río Hurtado'),
('salamanca'    ,'CO','Salamanca'),
('vicuna'       ,'CO','Vicuña'),

-- Valparaíso (VA)
('algarrobo'      ,'VA','Algarrobo'),
('cabildo'        ,'VA','Cabildo'),
('calera'         ,'VA','Calera'),
('calle-larga'    ,'VA','Calle Larga'),
('cartagena'      ,'VA','Cartagena'),
('casablanca'     ,'VA','Casablanca'),
('catemu'         ,'VA','Catemu'),
('concon'         ,'VA','Concón'),
('el-quisco'      ,'VA','El Quisco'),
('el-tabo'        ,'VA','El Tabo'),
('hijuelas'       ,'VA','Hijuelas'),
('isla-de-pascua' ,'VA','Isla de Pascua'),
('juan-fernandez' ,'VA','Juan Fernández'),
('la-cruz'        ,'VA','La Cruz'),
('la-ligua'       ,'VA','La Ligua'),
('limache'        ,'VA','Limache'),
('llaillay'       ,'VA','Llaillay'),
('los-andes'      ,'VA','Los Andes'),
('nogales'        ,'VA','Nogales'),
('olmue'          ,'VA','Olmué'),
('panquehue'      ,'VA','Panquehue'),
('papudo'         ,'VA','Papudo'),
('petorca'        ,'VA','Petorca'),
('puchuncavi'     ,'VA','Puchuncaví'),
('putaendo'       ,'VA','Putaendo'),
('quillota'       ,'VA','Quillota'),
('quilpue'        ,'VA','Quilpué'),
('quintero'       ,'VA','Quintero'),
('rinconada'      ,'VA','Rinconada'),
('san-antonio'    ,'VA','San Antonio'),
('san-esteban'    ,'VA','San Esteban'),
('san-felipe'     ,'VA','San Felipe'),
('santa-maria'    ,'VA','Santa María'),
('santo-domingo'  ,'VA','Santo Domingo'),
('valparaiso'     ,'VA','Valparaíso'),
('villa-alemana'  ,'VA','Villa Alemana'),
('vina-del-mar'   ,'VA','Viña del Mar'),
('zapallar'       ,'VA','Zapallar'),

-- Metropolitana (RM)
('alhue'              ,'RM','Alhué'),
('buin'               ,'RM','Buin'),
('calera-de-tango'    ,'RM','Calera de Tango'),
('cerrillos'          ,'RM','Cerrillos'),
('cerro-navia'        ,'RM','Cerro Navia'),
('colina'             ,'RM','Colina'),
('conchali'           ,'RM','Conchalí'),
('curacavi'           ,'RM','Curacaví'),
('el-bosque'          ,'RM','El Bosque'),
('el-monte'           ,'RM','El Monte'),
('estacion-central'   ,'RM','Estación Central'),
('huechuraba'         ,'RM','Huechuraba'),
('independencia'      ,'RM','Independencia'),
('isla-de-maipo'      ,'RM','Isla de Maipo'),
('la-cisterna'        ,'RM','La Cisterna'),
('la-florida'         ,'RM','La Florida'),
('la-granja'          ,'RM','La Granja'),
('la-pintana'         ,'RM','La Pintana'),
('la-reina'           ,'RM','La Reina'),
('lampa'              ,'RM','Lampa'),
('las-condes'         ,'RM','Las Condes'),
('lo-barnechea'       ,'RM','Lo Barnechea'),
('lo-espejo'          ,'RM','Lo Espejo'),
('lo-prado'           ,'RM','Lo Prado'),
('macul'              ,'RM','Macul'),
('maipu'              ,'RM','Maipú'),
('maria-pinto'        ,'RM','María Pinto'),
('melipilla'          ,'RM','Melipilla'),
('nunoa'              ,'RM','Ñuñoa'),
('padre-hurtado'      ,'RM','Padre Hurtado'),
('paine'              ,'RM','Paine'),
('pedro-aguirre-cerda','RM','Pedro Aguirre Cerda'),
('penaflor'           ,'RM','Peñaflor'),
('penalolen'          ,'RM','Peñalolén'),
('pirque'             ,'RM','Pirque'),
('providencia'        ,'RM','Providencia'),
('pudahuel'           ,'RM','Pudahuel'),
('puente-alto'        ,'RM','Puente Alto'),
('quilicura'          ,'RM','Quilicura'),
('quinta-normal'      ,'RM','Quinta Normal'),
('recoleta'           ,'RM','Recoleta'),
('renca'              ,'RM','Renca'),
('san-bernardo'       ,'RM','San Bernardo'),
('san-joaquin'        ,'RM','San Joaquín'),
('san-jose-de-maipo'  ,'RM','San José de Maipo'),
('san-miguel'         ,'RM','San Miguel'),
('san-pedro'          ,'RM','San Pedro'),
('san-ramon'          ,'RM','San Ramón'),
('santiago'           ,'RM','Santiago'),
('talagante'          ,'RM','Talagante'),
('tiltil'             ,'RM','Tiltil'),
('vitacura'           ,'RM','Vitacura'),

-- O'Higgins (LI)
('chimbarongo'       ,'LI','Chimbarongo'),
('chepica'           ,'LI','Chépica'),
('codegua'           ,'LI','Codegua'),
('coinco'            ,'LI','Coinco'),
('coltauco'          ,'LI','Coltauco'),
('donihue'           ,'LI','Doñihue'),
('graneros'          ,'LI','Graneros'),
('la-estrella'       ,'LI','La Estrella'),
('las-cabras'        ,'LI','Las Cabras'),
('litueche'          ,'LI','Litueche'),
('lolol'             ,'LI','Lolol'),
('machali'           ,'LI','Machalí'),
('malloa'            ,'LI','Malloa'),
('marchihue'         ,'LI','Marchihue'),
('nancagua'          ,'LI','Nancagua'),
('navidad'           ,'LI','Navidad'),
('olivar'            ,'LI','Olivar'),
('mostazal'          ,'LI','Mostazal'),
('palmilla'          ,'LI','Palmilla'),
('paredones'         ,'LI','Paredones'),
('peralillo'         ,'LI','Peralillo'),
('peumo'             ,'LI','Peumo'),
('pichidegua'        ,'LI','Pichidegua'),
('pichilemu'         ,'LI','Pichilemu'),
('placilla'          ,'LI','Placilla'),
('pumanque'          ,'LI','Pumanque'),
('quinta-de-tilcoco' ,'LI','Quinta de Tilcoco'),
('rancagua'          ,'LI','Rancagua'),
('rengo'             ,'LI','Rengo'),
('requinoa'          ,'LI','Requínoa'),
('san-fernando'      ,'LI','San Fernando'),
('san-vicente'       ,'LI','San Vicente'),
('santa-cruz'        ,'LI','Santa Cruz'),

-- Maule (ML)
('cauquenes'                ,'ML','Cauquenes'),
('chanco'                   ,'ML','Chanco'),
('colbun'                   ,'ML','Colbún'),
('constitucion'             ,'ML','Constitución'),
('curepto'                  ,'ML','Curepto'),
('curico'                   ,'ML','Curicó'),
('empedrado'                ,'ML','Empedrado'),
('hualane'                  ,'ML','Hualañé'),
('licanten'                 ,'ML','Licantén'),
('linares'                  ,'ML','Linares'),
('longavi'                  ,'ML','Longaví'),
('maule'                    ,'ML','Maule'),
('molina'                   ,'ML','Molina'),
('parral'                   ,'ML','Parral'),
('pelarco'                  ,'ML','Pelarco'),
('pelluhue'                 ,'ML','Pelluhue'),
('pencahue'                 ,'ML','Pencahue'),
('rauco'                    ,'ML','Rauco'),
('retiro'                   ,'ML','Retiro'),
('romeral'                  ,'ML','Romeral'),
('rio-claro'                ,'ML','Río Claro'),
('sagrada-familia'          ,'ML','Sagrada Familia'),
('san-clemente'             ,'ML','San Clemente'),
('san-javier-de-loncomilla' ,'ML','San Javier de Loncomilla'),
('san-rafael'               ,'ML','San Rafael'),
('talca'                    ,'ML','Talca'),
('teno'                     ,'ML','Teno'),
('vichuquen'                ,'ML','Vichuquén'),
('villa-alegre'             ,'ML','Villa Alegre'),
('yerbas-buenas'            ,'ML','Yerbas Buenas'),

-- Ñuble (NB)
('bulnes'        ,'NB','Bulnes'),
('chillan-viejo' ,'NB','Chillán Viejo'),
('chillan'       ,'NB','Chillán'),
('cobquecura'    ,'NB','Cobquecura'),
('coelemu'       ,'NB','Coelemu'),
('coihueco'      ,'NB','Coihueco'),
('el-carmen'     ,'NB','El Carmen'),
('ninhue'        ,'NB','Ninhue'),
('niquen'        ,'NB','Ñiquén'),
('pemuco'        ,'NB','Pemuco'),
('pinto'         ,'NB','Pinto'),
('portezuelo'    ,'NB','Portezuelo'),
('quillon'       ,'NB','Quillón'),
('quirihue'      ,'NB','Quirihue'),
('ranquil'       ,'NB','Ránquil'),
('san-carlos'    ,'NB','San Carlos'),
('san-fabian'    ,'NB','San Fabián'),
('san-ignacio'   ,'NB','San Ignacio'),
('san-nicolas'   ,'NB','San Nicolás'),
('treguaco'      ,'NB','Treguaco'),
('yungay'        ,'NB','Yungay'),

-- Biobío (BI)
('alto-biobio'         ,'BI','Alto Biobío'),
('antuco'              ,'BI','Antuco'),
('arauco'              ,'BI','Arauco'),
('cabrero'             ,'BI','Cabrero'),
('canete'              ,'BI','Cañete'),
('chiguayante'         ,'BI','Chiguayante'),
('concepcion'          ,'BI','Concepción'),
('contulmo'            ,'BI','Contulmo'),
('coronel'             ,'BI','Coronel'),
('curanilahue'         ,'BI','Curanilahue'),
('florida'             ,'BI','Florida'),
('hualpen'             ,'BI','Hualpén'),
('hualqui'             ,'BI','Hualqui'),
('laja'                ,'BI','Laja'),
('lebu'                ,'BI','Lebu'),
('los-alamos'          ,'BI','Los Álamos'),
('los-angeles'         ,'BI','Los Ángeles'),
('lota'                ,'BI','Lota'),
('mulchen'             ,'BI','Mulchén'),
('nacimiento'          ,'BI','Nacimiento'),
('negrete'             ,'BI','Negrete'),
('penco'               ,'BI','Penco'),
('quilaco'             ,'BI','Quilaco'),
('quilleco'            ,'BI','Quilleco'),
('san-pedro-de-la-paz' ,'BI','San Pedro de la Paz'),
('san-rosendo'         ,'BI','San Rosendo'),
('santa-barbara'       ,'BI','Santa Bárbara'),
('santa-juana'         ,'BI','Santa Juana'),
('talcahuano'          ,'BI','Talcahuano'),
('tirua'               ,'BI','Tirúa'),
('tome'                ,'BI','Tomé'),
('tucapel'             ,'BI','Tucapel'),
('yumbel'              ,'BI','Yumbel'),

-- Araucanía (AR)
('angol'           ,'AR','Angol'),
('carahue'         ,'AR','Carahue'),
('cholchol'        ,'AR','Cholchol'),
('collipulli'      ,'AR','Collipulli'),
('cunco'           ,'AR','Cunco'),
('curacautin'      ,'AR','Curacautín'),
('curarrehue'      ,'AR','Curarrehue'),
('ercilla'         ,'AR','Ercilla'),
('freire'          ,'AR','Freire'),
('galvarino'       ,'AR','Galvarino'),
('gorbea'          ,'AR','Gorbea'),
('lautaro'         ,'AR','Lautaro'),
('loncoche'        ,'AR','Loncoche'),
('lonquimay'       ,'AR','Lonquimay'),
('los-sauces'      ,'AR','Los Sauces'),
('lumaco'          ,'AR','Lumaco'),
('melipeuco'       ,'AR','Melipeuco'),
('nueva-imperial'  ,'AR','Nueva Imperial'),
('padre-las-casas' ,'AR','Padre las Casas'),
('perquenco'       ,'AR','Perquenco'),
('pitrufquen'      ,'AR','Pitrufquén'),
('pucon'           ,'AR','Pucón'),
('puren'           ,'AR','Purén'),
('renaico'         ,'AR','Renaico'),
('saavedra'        ,'AR','Saavedra'),
('temuco'          ,'AR','Temuco'),
('teodoro-schmidt' ,'AR','Teodoro Schmidt'),
('tolten'          ,'AR','Toltén'),
('traiguen'        ,'AR','Traiguén'),
('victoria'        ,'AR','Victoria'),
('vilcun'          ,'AR','Vilcún'),
('villarrica'      ,'AR','Villarrica'),

-- Los Ríos (LR)
('corral'      ,'LR','Corral'),
('futrono'     ,'LR','Futrono'),
('la-union'    ,'LR','La Unión'),
('lago-ranco'  ,'LR','Lago Ranco'),
('lanco'       ,'LR','Lanco'),
('los-lagos'   ,'LR','Los Lagos'),
('mariquina'   ,'LR','Mariquina'),
('mafil'       ,'LR','Máfil'),
('paillaco'    ,'LR','Paillaco'),
('panguipulli' ,'LR','Panguipulli'),
('rio-bueno'   ,'LR','Río Bueno'),
('valdivia'    ,'LR','Valdivia'),

-- Los Lagos (LL)
('ancud'                ,'LL','Ancud'),
('calbuco'              ,'LL','Calbuco'),
('castro'               ,'LL','Castro'),
('chaiten'              ,'LL','Chaitén'),
('chonchi'              ,'LL','Chonchi'),
('cochamo'              ,'LL','Cochamó'),
('curaco-de-velez'      ,'LL','Curaco de Vélez'),
('dalcahue'             ,'LL','Dalcahue'),
('fresia'               ,'LL','Fresia'),
('frutillar'            ,'LL','Frutillar'),
('futaleufu'            ,'LL','Futaleufú'),
('hualaihue'            ,'LL','Hualaihué'),
('llanquihue'           ,'LL','Llanquihue'),
('los-muermos'          ,'LL','Los Muermos'),
('maullin'              ,'LL','Maullín'),
('osorno'               ,'LL','Osorno'),
('palena'               ,'LL','Palena'),
('puerto-montt'         ,'LL','Puerto Montt'),
('puerto-octay'         ,'LL','Puerto Octay'),
('puerto-varas'         ,'LL','Puerto Varas'),
('puqueldon'            ,'LL','Puqueldón'),
('purranque'            ,'LL','Purranque'),
('puyehue'              ,'LL','Puyehue'),
('queilen'              ,'LL','Queilén'),
('quellon'              ,'LL','Quellón'),
('quemchi'              ,'LL','Quemchi'),
('quinchao'             ,'LL','Quinchao'),
('rio-negro'            ,'LL','Río Negro'),
('san-juan-de-la-costa' ,'LL','San Juan de la Costa'),
('san-pablo'            ,'LL','San Pablo'),

-- Aysén (AI)
('aysen'       ,'AI','Aysén'),
('chile-chico' ,'AI','Chile Chico'),
('cisnes'      ,'AI','Cisnes'),
('cochrane'    ,'AI','Cochrane'),
('coyhaique'   ,'AI','Coyhaique'),
('guaitecas'   ,'AI','Guaitecas'),
('lago-verde'  ,'AI','Lago Verde'),
('o’higgins'   ,'AI','O’Higgins'),
('rio-ibanez'  ,'AI','Río Ibáñez'),
('tortel'      ,'AI','Tortel'),

-- Magallanes (MA)
('antartica'        ,'MA','Antártica'),
('cabo-de-hornos'   ,'MA','Cabo de Hornos'),
('laguna-blanca'    ,'MA','Laguna Blanca'),
('natales'          ,'MA','Natales'),
('porvenir'         ,'MA','Porvenir'),
('primavera'        ,'MA','Primavera'),
('punta-arenas'     ,'MA','Punta Arenas'),
('rio-verde'        ,'MA','Río Verde'),
('san-gregorio'     ,'MA','San Gregorio'),
('timaukel'         ,'MA','Timaukel'),
('torres-del-paine' ,'MA','Torres del Paine');