INSERT INTO permissions (name, description, section)
VALUES
  ('list-role',  'Permite listar roles',  'role'),
    ('create-role',  'Permite crear roles',  'role'),
    ('update-role', 'Permite editar roles', 'role'),
    ('delete-role', 'Permite eliminar roles', 'role'),
    ('list-permission', 'Permite listar permisos', 'permission'),
    ('create-permission', 'Permite crear permisos', 'permission'),
    ('update-permission', 'Permite editar permisos', 'permission'),
    ('delete-permission', 'Permite eliminar permisos', 'permission'),
    ('list-user', 'Permite listar usuarios', 'user'),
    ('create-user', 'Permite crear usuarios', 'user'),
    ('update-user', 'Permite editar usuarios', 'user'),
    ('delete-user', 'Permite eliminar usuarios', 'user'),
    ('list-tenant', 'Permite listar tenants', 'tenant'),
    ('create-tenant', 'Permite crear tenants', 'tenant'),
    ('update-tenant', 'Permite editar tenants', 'tenant'),
    ('delete-tenant', 'Permite eliminar tenants', 'tenant'),
    ('list-region', 'Permite listar regiones', 'region'),
    ('list-commune', 'Permite listar comunas', 'commune'),
    ('list-country', 'Permite listar países', 'country'),
    ('list-currency', 'Permite listar monedas', 'currency'),
    ('list-bank', 'Permite listar bancos', 'bank'),
    ('list-policy', 'Permite listar politicas', 'policy'),
    ('create-policy', 'Permite crear politicas', 'policy'),
    ('update-policy', 'Permite editar politicas', 'policy'),
    ('delete-policy', 'Permite eliminar politicas', 'policy'),
    ('list-category', 'Permite listar categorías', 'category'),
    ('create-category', 'Permite crear categorías', 'category'),
    ('update-category', 'Permite editar categorías', 'category'),
    ('delete-category', 'Permite eliminar categorías', 'category'),
    ('list-policy-approver', 'Permite listar aprobadores de políticas', 'policy-approver'),
    ('create-policy-approver', 'Permite crear aprobadores de políticas', 'policy-approver'),
    ('update-policy-approver', 'Permite editar aprobadores de políticas', 'policy-approver'),
    ('delete-policy-approver', 'Permite eliminar aprobadores de políticas', 'policy-approver'),
    ('list-policy-submitter', 'Permite listar postulantes de políticas', 'policy-submitter'),
    ('create-policy-submitter', 'Permite crear postulantes de políticas', 'policy-submitter'),
    ('update-policy-submitter', 'Permite editar postulantes de políticas', 'policy-submitter'),
    ('delete-policy-submitter', 'Permite eliminar postulantes de políticas', 'policy-submitter'),
    ('list-policy-report-status', 'Permite listar estados de reportes de política', 'policy-report-status'),
    ('create-policy-report-status', 'Permite crear estados de reportes de política', 'policy-report-status'),
    ('update-policy-report-status', 'Permite editar estados de reportes de política', 'policy-report-status'),
    ('delete-policy-report-status', 'Permite eliminar estados de reportes de política', 'policy-report-status'),
    ('list-policy-field', 'Permite listar campos de política', 'policy-field'),
    ('create-policy-field', 'Permite crear campos de política', 'policy-field'),
    ('update-policy-field', 'Permite editar campos de política', 'policy-field'),
    ('delete-policy-field', 'Permite eliminar campos de política', 'policy-field'),
    ('list-report-expense', 'Permite listar reportes de gastos', 'report-expense'),
    ('create-report-expense', 'Permite crear reportes de gastos', 'report-expense'),
    ('update-report-expense', 'Permite editar reportes de gastos', 'report-expense'),
    ('delete-report-expense', 'Permite eliminar reportes de gastos', 'report-expense'),
    ('list-report-expense-details', 'Permite listar detalles de reportes de gastos', 'report-expense-detail'),
    ('create-report-expense-details', 'Permite crear detalles de reportes de gastos', 'report-expense-detail'),
    ('update-report-expense-details', 'Permite editar detalles de reportes de gastos', 'report-expense-detail'),
    ('delete-report-expense-details', 'Permite eliminar detalles de reportes de gastos', 'report-expense-detail'),
    ('list-report-expense-record', 'Permite listar registros de reportes de gastos', 'report-expense-record'),
    ('create-report-expense-record', 'Permite crear registros de reportes de gastos', 'report-expense-record'),
    ('update-report-expense-record', 'Permite editar registros de reportes de gastos', 'report-expense-record'),
    ('delete-report-expense-record', 'Permite eliminar registros de reportes de gastos', 'report-expense-record'),
    ('list-report-expense-comment', 'Permite listar comentarios de reportes de gastos', 'report-expense-comment'),
    ('create-report-expense-comment', 'Permite crear comentarios de reportes de gastos', 'report-expense-comment'),
    ('update-report-expense-comment', 'Permite editar comentarios de reportes de gastos', 'report-expense-comment'),
    ('delete-report-expense-comment', 'Permite eliminar comentarios de reportes de gastos', 'report-expense-comment'),
    ('list-report-expense-approver', 'Permite listar aprobadores de reportes de gastos', 'report-expense-approver'),
    ('create-report-expense-approver', 'Permite crear aprobadores de reportes de gastos', 'report-expense-approver'),
    ('update-report-expense-approver', 'Permite editar aprobadores de reportes de gastos', 'report-expense-approver'),
    ('delete-report-expense-approver', 'Permite eliminar aprobadores de reportes de gastos', 'report-expense-approver'),
    ('list-expense-gallery', 'Permite listar galerías de gastos', 'expense-gallery'),
    ('create-expense-gallery', 'Permite crear galerías de gastos', 'expense-gallery'),
    ('update-expense-gallery', 'Permite editar galerías de gastos', 'expense-gallery'),
    ('delete-expense-gallery', 'Permite eliminar galerías de gastos', 'expense-gallery')
ON CONFLICT (name) DO NOTHING;